---
title: "Cell Size Sensitivity"
runtime: shiny
output: html_document
---

```{r setup, include = FALSE}
#mostly copied from kde.R, see there for explanatory comments
library(sp)
library(maptools)
library(splancs)
library(data.table)
library(foreign)
library(rgeos)

prj = CRS("+init=epsg:2913")

#making it easier to deploy -- apparently the deployment
#  tool scans the R script for file names, but misses
#  those found in list.files and the extra files
#  associated with .shp files
files.dummy = 
  c("data/NIJ2016_JAN01_JUL31.dbf",
    "data/Portland_Police_Districts.cpg",
    "data/Portland_Police_Districts.dbf", 
    "data/Portland_Police_Districts.prj", 
    "data/Portland_Police_Districts.sbn",
    "data/Portland_Police_Districts.sbx", 
    "data/Portland_Police_Districts.shp", 
    "data/Portland_Police_Districts.shp.xml",
    "data/Portland_Police_Districts.shx")

set.seed(922574)
crimes = 
  setDT(read.dbf("data/NIJ2016_JAN01_JUL31.dbf", 
                 as.is = TRUE))[!is.na(occ_date)]

setnames(crimes, tolower(names(crimes)))
crimes[ , occ_date := as.IDate(occ_date)]

crimes.map <-
  SpatialPointsDataFrame(
    coords = crimes[ , cbind(x_coordina, y_coordina)],
    data = crimes[ , -paste0(c('x', 'y'), '_coordina'), with = FALSE],
    proj4string = prj
  )

portland = 
  gUnaryUnion(readShapePoly("data/Portland_Police_Districts.shp",
                            proj4string = prj))

bb = bbox(portland)
grids = lapply(list("rec250x250" = c(250, 250), "rec600x600" = c(600, 600), 
                    "rec460x460" = c(460, 460), "rec370x750" = c(370, 750)),
               function(dims) 
                 GridTopology(cellcentre.offset = bb[ , 'min'],
                              cellsize = dims,
                              cells.dim = round(apply(bb, 1L, diff)/dims)))

outerRings <- Filter(function(pol) pol@ringDir==1, 
                     portland@polygons[[1L]]@Polygons)
outerBounds <- SpatialPolygons(list(Polygons(outerRings, ID=1)))
portland.chull <- gConvexHull(portland)
portland.simp <- 
  SpatialPolygons(list(Polygons(list(
    outerBounds@polygons[[1L]]@Polygons[[5L]]), ID=1)))

log.min = function(x) {
  m = min(x[x>0])
  x[x == 0] = m/10
  log10(x)
}

compute.kdes <- function(df, grd.grdtop, bw){
  kde.all <- 
    spkernel2d(pts = df, h0 = bw, grd = grd.grdtop,
               poly = portland.simp@polygons[[1L]]@Polygons[[1L]]@coords)
  kde.street <-
    spkernel2d(pts = df[df$category=='STREET CRIMES', ],
               h0 = bw, grd = grd.grdtop,
               poly = portland.simp@polygons[[1L]]@Polygons[[1L]]@coords)
  kde.burglary <- 
    spkernel2d(pts = df[df$category=='BURGLARY', ], 
               poly = portland.simp@polygons[[1L]]@Polygons[[1L]]@coords, 
               h0 = bw, grd = grd.grdtop)
  kde.vehicle <- 
    spkernel2d(pts = df[df$category=='MOTOR VEHICLE THEFT', ], 
               poly = portland.simp@polygons[[1L]]@Polygons[[1L]]@coords, 
               h0 = bw, grd = grd.grdtop)
  data.frame(all = kde.all/sum(kde.all, na.rm=TRUE), 
             street = kde.street/sum(kde.street, na.rm=TRUE), 
             burglary = kde.burglary/sum(kde.burglary, na.rm=TRUE), 
             vehicle = kde.vehicle/sum(kde.vehicle, na.rm=TRUE))
}

intervals = 
  list("feb" = as.IDate(c("2016-02-01", "2016-02-28")),
       "w1" = as.IDate(c("2016-03-01", "2016-03-07")),
       "w2" = as.IDate(c("2016-03-01", "2016-03-14")),
       "m1" = as.IDate(c("2016-03-01", "2016-03-31")),
       "m3" = as.IDate(c("2016-03-01", "2016-05-31")))
```

## Choose Grid

```{r choose_grid, echo = FALSE}
inputPanel(
  selectInput("grd", label = "Grid Size",
              choices = c("250ft x 250ft Rectangle" = "rec250x250",
                          "600ft x 600ft Rectangle" = "rec600x600",
                          "460ft x 460ft Rectangle" = "rec460x460",
                          "370ft x 750ft Rectangle" = "rec370x750"),
              selected = "rec600x600")
)
```

##KDEs

```{r kdes, echo = FALSE}
inputPanel(
  selectInput("horiz", label = "Timeframe",
              choices = c("February 2016" = "feb",
                          "March 1 - 7, 2016" = "w1",
                          "March 1 - 14, 2016" = "w2",
                          "March 2016" = "m1",
                          "March - May 2016" = "m3"),
              selected = "feb"),
  numericInput("bw", label = "Bandwidth (ft)", value = 2400,
               min = 0, max = 1.28e5, step = 100)
)

renderPlot(
  spplot(
    SpatialGridDataFrame(
      grids[[input$grd]], 
      data = compute.kdes(
        df = crimes.map[crimes.map$occ_date %between% 
                          intervals[[input$horiz]], ],
        grd.grdtop = grids[[input$grd]], bw = input$bw
      )
    ), checkEmptyRC = FALSE, col.regions = terrain.colors(16), cuts = 15,
    main = 'Kernel Density Estimate with Specified Parameters')
)

renderPlot(
  spplot(
    SpatialGridDataFrame(
      grids[[input$grd]], 
      data = log.min(compute.kdes(
        df = crimes.map[crimes.map$occ_date %between% 
                          intervals[[input$horiz]], ],
        grd.grdtop = grids[[input$grd]], bw = input$bw
      ))
    ), checkEmptyRC = FALSE, col.regions = terrain.colors(50), cuts = 49,
    main = 'Kernel Density Estimate with Specified Parameters (Log-10 Scale)')
)
```
