#!/bin/sh
sh fit_features.bash 600 600 0 3 4 600 1e-5 1e-4 .5 1 0 .5 1w all
echo '+++++++++++++++++ #2 +++++++++++++++++++++'
sh fit_features.bash 250 250 0 3 4 200 1e-5 1e-4 .5 1 0 .5 1w all
echo '+++++++++++++++++ #3 +++++++++++++++++++++'
sh fit_features.bash 250 250 0 5 4 200 1e-5 1e-4 .5 1 0 .5 1w all
echo '+++++++++++++++++ #4 +++++++++++++++++++++'
sh fit_features.bash 250 250 1 3 4 200 1e-5 1e-4 .5 1 0 .5 1w all

